//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRA_Frontend.ETK.ETKWrap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QRA_Frontend.ETK.ETKWrap.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///class Options:
        ///	CalculateRho, CalculateP, CalculateT, Unknown=range(4)
        ///
        ///result=[]
        ///CalculationOption=Options.Unknown
        ///
        ///
        ///try:
        ///	T_H2
        ///	P_H2
        ///	CalculationOption=Options.CalculateRho
        ///except NameError:
        ///	try:
        ///		T_H2
        ///		rho_H2
        ///		CalculationOption=Options.CalculateP
        ///	except NameError:
        ///		try:
        ///			P_H2
        ///			rho_H2
        ///			CalculationOption=Options.CalculateT
        ///		except NameError:
        ///			CalculationOption=Options.Unknown
        ///
        ///if (CalculationOption==Options.CalculateRho):
        ///	result.append(&quot;rho:&quot; + str(Thermo_wrapper( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThermoWrapperFileMain {
            get {
                return ResourceManager.GetString("ThermoWrapperFileMain", resourceCulture);
            }
        }
    }
}
