//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandiaNationalLaboratories.Hyram {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotSavePath {
            get {
                return ((string)(this["plotSavePath"]));
            }
            set {
                this["plotSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string workspaceSavePath {
            get {
                return ((string)(this["workspaceSavePath"]));
            }
            set {
                this["workspaceSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Meter")]
        public string MFROrificeDiamDistUnit {
            get {
                return ((string)(this["MFROrificeDiamDistUnit"]));
            }
            set {
                this["MFROrificeDiamDistUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa")]
        public string MFRPressureUnit {
            get {
                return ((string)(this["MFRPressureUnit"]));
            }
            set {
                this["MFRPressureUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Liter")]
        public string MFRVolumeUnit {
            get {
                return ((string)(this["MFRVolumeUnit"]));
            }
            set {
                this["MFRVolumeUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kelvin")]
        public string MFRTempUnit {
            get {
                return ((string)(this["MFRTempUnit"]));
            }
            set {
                this["MFRTempUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kelvin")]
        public string TPDTempUnit {
            get {
                return ((string)(this["TPDTempUnit"]));
            }
            set {
                this["TPDTempUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa")]
        public string TPDPressureUnit {
            get {
                return ((string)(this["TPDPressureUnit"]));
            }
            set {
                this["TPDPressureUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KilogramPerCubicMeter")]
        public string TPDDensitiyUnit {
            get {
                return ((string)(this["TPDDensitiyUnit"]));
            }
            set {
                this["TPDDensitiyUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPDDensityControl {
            get {
                return ((bool)(this["TPDDensityControl"]));
            }
            set {
                this["TPDDensityControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TPDPressureControl {
            get {
                return ((bool)(this["TPDPressureControl"]));
            }
            set {
                this["TPDPressureControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TPDTempControl {
            get {
                return ((bool)(this["TPDTempControl"]));
            }
            set {
                this["TPDTempControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPHorizLines {
            get {
                return ((bool)(this["OPHorizLines"]));
            }
            set {
                this["OPHorizLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPMarkDots {
            get {
                return ((bool)(this["OPMarkDots"]));
            }
            set {
                this["OPMarkDots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa")]
        public string TMPressureUnit {
            get {
                return ((string)(this["TMPressureUnit"]));
            }
            set {
                this["TMPressureUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kelvin")]
        public string TMTempUnit {
            get {
                return ((string)(this["TMTempUnit"]));
            }
            set {
                this["TMTempUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kilogram")]
        public string TMMassUnit {
            get {
                return ((string)(this["TMMassUnit"]));
            }
            set {
                this["TMMassUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CubicMeter")]
        public string TMVolumeUnit {
            get {
                return ((string)(this["TMVolumeUnit"]));
            }
            set {
                this["TMVolumeUnit"] = value;
            }
        }
    }
}
